accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',TemplateView.as_view(template_name="country/base.html")),
     path('country/',include('country.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

country/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from country import views


app_name = 'country'
urlpatterns = [
    path('',views.index,name='index'),
    path('country/<int:country_id>/',views.details,name='details'),
    path('add/',views.add_country,name='add_country'),
    path('edit/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

    path('country-rest/',views.CountryListView.as_view(),name="list_country"),
    path('country-rest/<int:pk>',views.CountryDetailView.as_view(),name="detail_country"),
    
]

country/models.py
from django.db import models

# Create your models here.
class country(models.Model):

    countryName = models.CharField(max_length=50)
    currency = models.CharField(max_length=50)
    countryImage = models.ImageField(default='default.jpg',upload_to='countryImage/')
    nativeName =models.CharField(max_length=50)
    capital = models.CharField(max_length=50)
    population = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    countryCode = models.CharField(max_length=50)
    language = models.CharField(max_length=50)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.countryName

country/forms.py
from django import forms
from .models import country

class countryForm(forms.ModelForm):
    class Meta:

        model = country
        fields = '__all__'

country/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from country.models import country
from .forms import countryForm
from django.contrib.auth.decorators import login_required
from rest_framework import generics,status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .models import country
from .serializers import CountrySerializer

# Create your views here.
@login_required
def index(request):
    country_list = country.objects.all()
    context ={
        'country_list':country_list
    }
    return render(request,'country/index.html',context)

@login_required
def details(request,country_id): 
    try:
        countrys = country.objects.get(id=country_id)
    except country.DoesNotExist:
        countrys = None
    # countrys = country.objects.get(id=country_id)
    return render(request,'country/countryList.html',{'country':countrys})

@login_required
def add_country(request):
    if request.method == "POST":
        countryName=request.POST.get('countryName',)
        currency=request.POST.get('currency',)
        countryImage=request.FILES['countryImage']
        nativeName=request.POST.get('nativeName',)
        capital=request.POST.get('capital',)
        population=request.POST.get('population',)
        countryCode=request.POST.get('countryCode',)
        language=request.POST.get('language',)
        region=request.POST.get('region',)
        countrys = country(countryName=countryName,currency=currency,countryImage=countryImage,nativeName=nativeName,capital=capital,population=population,countryCode=countryCode,language=language,region=region,)
        countrys.save()
        return redirect('/country')
    return render(request,'country/addCountry.html')

@login_required
def update(request,id):
    try:
        countrys = country.objects.get(id=id)
    except country.DoesNotExist:
        countrys = None
    # countrys = country.objects.get(id=id)
    form = countryForm(request.POST or None, request.FILES, instance=countrys)
    if form.is_valid():
        form.save()
        return redirect('/country')
    return render(request,'country/editCountry.html',{'form':form,'country':countrys})

@login_required
def delete(request,id):
    if request.method == "POST":
        try:
            countrys=country.objects.get(id=id)
        except country.DoesNotExist:
            countrys = None
        # countrys=country.objects.get(id=id)
        countrys.delete()
        return redirect('/country')
    return render(request,'country/deleteCountry.html')

class CountryListView(generics.ListCreateAPIView):
    queryset = country.objects.all()
    serializer_class = CountrySerializer

class CountryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = country.objects.all()
    serializer_class = CountrySerializer

@api_view(['GET','POST','PATCH','PUT','DELETE'])
def saveCountry(request):
    if request.method =="POST":
        saveSerialize = CountrySerializer(data=request.data)
        if saveSerialize.is_valid():
            saveSerialize.save()
            return Response(saveSerialize.data,status=status.HTTP_201_CREATED)
        return Response(saveSerialize.data,status=status.HTTP_400_BAD_REQUEST)

country/templates/country/addCountry.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="countryName" id="name" placeholder="Enter Country Name"><br>
    <input type="text" name="currency" id="price" placeholder="Enter currency"><br>
    <input type="text" name="nativeName" id="nativeName" placeholder="Enter Native Name"><br>
    <input type="text" name="capital" id="capital" placeholder="Enter capital"><br>
    <input type="text" name="population" id="population" placeholder="Enter population"><br>
    <input type="text" name="region" id="region" placeholder="Enter region"><br>
    <input type="text" name="countryCode" id="countryCode" placeholder="Enter Country Code"><br>
    <input type="text" name="language" id="language" placeholder="Enter Language"><br>
    <input type="file" name="countryImage" id="countryImage"><br>
    
    <input type="submit" name="submit" id="submit">
</form>

country/templates/country/base.html
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Countries</title>
</head>
<body>
    <!-- As a heading -->
  <nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Countries</span>
  </nav>
  {% if user.is_authenticated %}
    {{user}}
    <a class='float-right' href="{% url 'account_logout' %}">Sign Out</a>
  {% else %}
    <a class="btn btn-outline-primary" href="{% provider_login_url 'google' %}">Login With Google</a>
    <a class="btn btn-outline-primary" href="{% provider_login_url 'facebook' method='js_sdk' %}">Facebook Connect</a>
  {% endif %}

  {% block body %}
  
  {% endblock %}
</body>
</html>

country/templates/country/countryList.html
{% extends 'country/base.html' %}

{% block body %}

<div class="container">
   
<div class="card" style="width: 30rem;">
       
    <div class="card-body">
        <div class="row">
          <div class="col-sm-6">
            <img class="card-img" src="{{country.countryImage.url}}" alt="Card image cap">
           </div>
         <div class="col-sm-6">

            <br>
        Country Name: {{country.countryName}}<br>
        Currency: {{country.currency}}<br><br>
        Native Name: {{country.nativeName}}<br>
        Capital: {{country.capital}}<br>
        Population: {{country.population}}<br>
        Region: {{country.region}}<br>
        Country Code:{{country.countryCode}}<br>
        Languages: {{country.language}}<br>
       
      
        <a class ="btn btn-warning" href="{% url 'country:update' country.id %}">Update</a>
        <a class ="btn btn-danger" href="{% url 'country:delete' country.id %}">DELETE</a>
          

        </div>  
        </div>  
    </div>
 </div>

{% endblock %}

country/templates/country/deleteCountry.html
<form method="POST">
    {% csrf_token %}
    Are you sure to delete?
    <input type="submit">
</form>

country/templates/country/editCountry.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="submit" placeholder="UPDATE">
</form>

country/templates/country/index.html
{% extends 'country/base.html' %}
  
  {% block body %}

  <div class="container">
    
      {% for country in country_list %}

      <div class="card" style="width: 30rem;">
       
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                <img class="card-img" src="{{country.countryImage.url}}" alt="Card image cap">
                </div>
                <div class="col-sm-6">
               <h2 class="card-title">{{country.countryName}}</h2>
                <p class="card-text">{{country.currency}}</p>
               <!-- <small>Current date and time:23rd jan 2020, 14.34</small> -->
               <a href="#" class="btn btn-outline-primary">Show Map</a> &nbsp;
               <a href="{% url 'country:details' country.id %}" class="btn btn-outline-primary">Details</a>
               <!-- <a href="{% url 'country:details' country.id %}" class="btn btn-outline-primary">View Details</a> -->
                </div>  
            </div>  
        </div>
      </div>
    
      {% endfor %}

      <a href="{% url 'country:add_country' %}" class="btn btn-outline-primary">Add New Country</a>
    </div>
  </div>    
   
  {% endblock %}